import type { Metadata } from "next";
import "./globals.css";
import {TopBar} from "@/src/components/TopBar/TopBar";
import {ReactNode} from "react";
import {Toaster} from "sonner";
import {SignupProvider} from "@/utils/functions/signUpStore";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import {dark, shadcn} from '@clerk/ui/themes'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children} : {children: ReactNode})
{
  return (
    <ClerkProvider
        appearance={{
            theme: dark,
        }}
    >
      <html
        lang="en"
        className="h-full antialiased scrollbar-gutter-stable dsbleeoc idc0_350"
        // I honestly do not know what these last classnames are
      >
        <body className="min-h-full flex flex-col">
            <SignupProvider>
              <TopBar />
              <Toaster theme={"dark"} duration={2000} />
              {children}
            </SignupProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
