import type { Metadata } from "next";
import "./globals.css";
import {TopBar} from "@/src/components/TopBar/TopBar";
import {ReactNode} from "react";
import {Toaster} from "sonner";
import {SignupProvider} from "@/utils/functions/signUpStore";
import { ClerkProvider} from '@clerk/nextjs'
import {dark} from '@clerk/ui/themes'
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const priestacy = localFont({
    src: "../fonts/Priestacy.otf",
    variable: "--font-priestacy",
    display: "swap",
});

const orangeAvenue = localFont({
    src: "../fonts/OrangeAvenueDEMO-Regular.otf",
    variable: "--font-orangeAvenue",
    display: "swap",
});

const astralMadesly = localFont({
    src: "../fonts/Astrel-Madesly-Personal-Use-Only.ttf",
    variable: "--font-astralMadesly",
    display: "swap",
});

export default function RootLayout({children} : {children: ReactNode})
{
  return (
    <html
      lang="en"
      className={`h-full antialiased scrollbar-gutter-stable ${priestacy.variable} ${orangeAvenue.variable} ${astralMadesly.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
      <ClerkProvider
          appearance={{
              theme: dark,
          }}>
          <SignupProvider>
              <TopBar/>
              <Toaster theme={"dark"} duration={2000}/>
              <div className="mt-[22vw] lg:mt-0" />
              {children}
          </SignupProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
